services:
  callcadence-api:
    image: carpdeus/callcadence.api:latest
    restart: unless-stopped
    ports:
      - 5110:8080
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:Production}"
      ConnectionStrings__CallCadenceDb: "${CALLCADENCE_DB:? CALLCADENCE_DB is Required}"
      ConnectionStrings__CallCadenceHangfireDb: "${CALLCADENCE_HANGFIRE_DB:? CALLCADENCE_HANGFIRE_DB is Required}"
      Sentry__Dsn: "${SENTRY_DSN:-}"
      Sentry__Environment: "${ASPNETCORE_ENVIRONMENT:Production}"
      # For the Jwt__SigningKey, you can create one using:
      # Linux: openssl rand -hex 32
      # https://randomkeygen.com/jwt-secret
      Jwt__SigningKey: "A-strong-secret-string-like-the-secret-sauce-at-your-favorite-restaurant"
      Jwt__Issuer: "CallCadence.API"
      Jwt__Audience: "CallCadence.UI"
      Jwt__ExpiryMinutes: 60
      # Make sure the AllowedUiReturnUrls have the trailing slash
      AllowedUiReturnUrls: "${UI_URI},${API_URI}"

  callcadence-ui:
    image: carpdeus/callcadence.ui:latest
    restart: unless-stopped
    ports:
      - 5294:8080
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:Production}"
      Api__BaseUrl: "${API_URI}"
    depends_on:
      - callcadence-api
